name: Deploy Kubernetes Cluster with Terraform deployment

on:
  push:
    branches:
      - main


jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Check terraform fmt
        run: |
          pwd
          ls -la
          cd AWS-k8S-Clusterset-Ec2
          ls -la
          terraform fmt -check ./terraform



      - name: Terraform Format
        working-directory: ./terraform
        run:  terraform fmt -check ./terraform

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
